spring:
  application:
    name: chat-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    access-token-expiry: 900000     # 15 minutes
    refresh-token-expiry: 604800000 # 7 days

  admin:
    username: ${APP_ADMIN_USERNAME}
    email: ${APP_ADMIN_EMAIL}
    password: ${APP_ADMIN_PASSWORD}

server:
  address: 0.0.0.0
  port: 8080

