spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:mysql://localhost:3306/chat_service_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    access-token-expiry: 900000     # 15 minutes
    refresh-token-expiry: 604800000 # 7 days

server:
  address: 0.0.0.0
  port: 8080